/*
 * This source file was generated by the Gradle 'init' task
 */
package submission.service;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void  context() {
        assertTrue( true );
    }
}
